2023-07-26 08:19:52.414 UTC [1028977] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-26 08:19:52.414 UTC [1028977] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-26 08:19:52.420 UTC [1028977] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-26 08:19:52.429 UTC [1028980] LOG:  database system was shut down at 2023-07-26 08:19:52 UTC
2023-07-26 08:19:52.436 UTC [1028977] LOG:  database system is ready to accept connections
2023-07-26 08:19:52.848 UTC [1029004] ERROR:  could not create unique index "idx_badindex_n"
2023-07-26 08:19:52.848 UTC [1029004] DETAIL:  Key (n)=(10) is duplicated.
2023-07-26 08:19:52.848 UTC [1029004] STATEMENT:  CREATE UNIQUE INDEX CONCURRENTLY idx_badindex_n ON tbl_badindex (n);
2023-07-26 08:19:57.333 UTC [1029177] ERROR:  permission denied for schema repack at character 8
2023-07-26 08:19:57.333 UTC [1029177] STATEMENT:  select repack.version(), repack.version_sql()
2023-07-26 08:19:59.098 UTC [1029266] ERROR:  table name not found for OID 1
2023-07-26 08:19:59.098 UTC [1029266] STATEMENT:  SELECT repack.get_order_by('issue321_idx'::regclass::oid, 1);
2023-07-26 08:19:59.099 UTC [1029266] ERROR:  cache lookup failed for index 1
2023-07-26 08:19:59.099 UTC [1029266] STATEMENT:  SELECT repack.get_order_by(1, 1);
