2023-07-21 21:59:58.831 UTC [1508770] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 21:59:58.831 UTC [1508770] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 21:59:58.841 UTC [1508770] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 21:59:58.850 UTC [1508773] LOG:  database system was shut down at 2023-07-21 21:59:58 UTC
2023-07-21 21:59:58.857 UTC [1508770] LOG:  database system is ready to accept connections
2023-07-21 21:59:59.076 UTC [1508771] LOG:  checkpoint starting: immediate force wait
2023-07-21 21:59:59.110 UTC [1508771] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.006 s, total=0.034 s; sync files=7, longest=0.004 s, average=0.001 s; distance=4204 kB, estimate=4204 kB
2023-07-21 21:59:59.310 UTC [1508821] ERROR:  not a Python mapping
2023-07-21 21:59:59.310 UTC [1508821] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-21 21:59:59.310 UTC [1508821] STATEMENT:  SELECT test1bad();
2023-07-21 21:59:59.318 UTC [1508821] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-21 21:59:59.318 UTC [1508821] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-21 21:59:59.318 UTC [1508821] STATEMENT:  SELECT test2dom('bar');
2023-07-21 22:00:31.085 UTC [1508771] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:00:31.173 UTC [1508771] LOG:  checkpoint complete: wrote 755 buffers (4.6%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.018 s, sync=0.024 s, total=0.088 s; sync files=254, longest=0.006 s, average=0.001 s; distance=140969 kB, estimate=140969 kB
2023-07-21 22:01:02.631 UTC [1508771] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:01:02.683 UTC [1508771] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.008 s, sync=0.004 s, total=0.053 s; sync files=4, longest=0.003 s, average=0.001 s; distance=136766 kB, estimate=140548 kB
2023-07-21 22:01:02.743 UTC [1508770] LOG:  received fast shutdown request
2023-07-21 22:01:02.746 UTC [1508770] LOG:  aborting any active transactions
2023-07-21 22:01:02.747 UTC [1508770] LOG:  background worker "logical replication launcher" (PID 1508776) exited with exit code 1
2023-07-21 22:01:02.747 UTC [1508771] LOG:  shutting down
2023-07-21 22:01:02.750 UTC [1508771] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:01:02.769 UTC [1508771] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.001 s, total=0.022 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126493 kB
2023-07-21 22:01:02.788 UTC [1508770] LOG:  database system is shut down
2023-07-21 22:01:03.504 UTC [1508958] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:01:03.505 UTC [1508958] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:01:03.510 UTC [1508958] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:01:03.517 UTC [1508961] LOG:  database system was shut down at 2023-07-21 22:01:03 UTC
2023-07-21 22:01:03.527 UTC [1508958] LOG:  database system is ready to accept connections
2023-07-21 22:01:03.796 UTC [1508959] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:01:03.820 UTC [1508959] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.025 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4047 kB, estimate=4047 kB
2023-07-21 22:01:03.954 UTC [1509002] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-21 22:01:03.954 UTC [1509002] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-21 22:01:03.954 UTC [1509002] STATEMENT:  SELECT testComplexNumbers();
2023-07-21 22:01:35.647 UTC [1508959] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:01:35.775 UTC [1508959] LOG:  checkpoint complete: wrote 548 buffers (3.3%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.020 s, sync=0.061 s, total=0.129 s; sync files=252, longest=0.007 s, average=0.001 s; distance=140871 kB, estimate=140871 kB
2023-07-21 22:02:07.195 UTC [1508959] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:02:07.246 UTC [1508959] LOG:  checkpoint complete: wrote 10 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.007 s, sync=0.004 s, total=0.052 s; sync files=4, longest=0.003 s, average=0.001 s; distance=136525 kB, estimate=140436 kB
2023-07-21 22:02:07.294 UTC [1508958] LOG:  received fast shutdown request
2023-07-21 22:02:07.297 UTC [1508958] LOG:  aborting any active transactions
2023-07-21 22:02:07.298 UTC [1508958] LOG:  background worker "logical replication launcher" (PID 1508964) exited with exit code 1
2023-07-21 22:02:07.298 UTC [1508959] LOG:  shutting down
2023-07-21 22:02:07.301 UTC [1508959] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:02:07.317 UTC [1508959] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.019 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126393 kB
2023-07-21 22:02:07.336 UTC [1508958] LOG:  database system is shut down
2023-07-21 22:02:07.969 UTC [1509086] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:02:07.969 UTC [1509086] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:02:07.975 UTC [1509086] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:02:07.983 UTC [1509089] LOG:  database system was shut down at 2023-07-21 22:02:07 UTC
2023-07-21 22:02:07.988 UTC [1509086] LOG:  database system is ready to accept connections
2023-07-21 22:02:08.259 UTC [1509087] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:02:08.295 UTC [1509087] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.005 s, total=0.036 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4352 kB, estimate=4352 kB
2023-07-21 22:02:08.429 UTC [1509136] ERROR:  ltree syntax error at character 1
2023-07-21 22:02:08.429 UTC [1509136] CONTEXT:  while creating return value
	PL/Python function "test2"
2023-07-21 22:02:08.429 UTC [1509136] STATEMENT:  SELECT test2();
2023-07-21 22:02:40.095 UTC [1509087] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:02:40.185 UTC [1509087] LOG:  checkpoint complete: wrote 687 buffers (4.2%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.021 s, sync=0.031 s, total=0.091 s; sync files=252, longest=0.003 s, average=0.001 s; distance=141283 kB, estimate=141283 kB
2023-07-21 22:03:11.560 UTC [1509087] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:03:11.616 UTC [1509087] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.007 s, sync=0.004 s, total=0.057 s; sync files=4, longest=0.003 s, average=0.001 s; distance=137073 kB, estimate=140862 kB
2023-07-21 22:03:11.654 UTC [1509086] LOG:  received fast shutdown request
2023-07-21 22:03:11.658 UTC [1509086] LOG:  aborting any active transactions
2023-07-21 22:03:11.660 UTC [1509086] LOG:  background worker "logical replication launcher" (PID 1509092) exited with exit code 1
2023-07-21 22:03:11.660 UTC [1509087] LOG:  shutting down
2023-07-21 22:03:11.663 UTC [1509087] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:03:11.682 UTC [1509087] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.022 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126776 kB
2023-07-21 22:03:11.722 UTC [1509086] LOG:  database system is shut down
2023-07-21 22:03:12.398 UTC [1509266] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:03:12.398 UTC [1509266] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:03:12.405 UTC [1509266] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:03:12.414 UTC [1509269] LOG:  database system was shut down at 2023-07-21 22:03:12 UTC
2023-07-21 22:03:12.421 UTC [1509266] LOG:  database system is ready to accept connections
2023-07-21 22:03:12.597 UTC [1509291] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:03:12.597 UTC [1509291] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:03:12.597 UTC [1509291] STATEMENT:  SELECT test2();
2023-07-21 22:03:12.599 UTC [1509291] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:03:12.599 UTC [1509291] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:03:12.599 UTC [1509291] STATEMENT:  SELECT test2();
2023-07-21 22:03:12.610 UTC [1509291] ERROR:  cannot drop extension hstore because other objects depend on it
2023-07-21 22:03:12.610 UTC [1509291] DETAIL:  extension hstore_plpython3u depends on extension hstore
2023-07-21 22:03:12.610 UTC [1509291] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023-07-21 22:03:12.610 UTC [1509291] STATEMENT:  DROP EXTENSION hstore;
2023-07-21 22:03:12.698 UTC [1509297] ERROR:  cannot drop extension hstore because other objects depend on it
2023-07-21 22:03:12.698 UTC [1509297] DETAIL:  extension hstore_plpython3u depends on extension hstore
2023-07-21 22:03:12.698 UTC [1509297] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023-07-21 22:03:12.698 UTC [1509297] STATEMENT:  DROP EXTENSION hstore;
2023-07-21 22:03:12.758 UTC [1509303] ERROR:  type "foo" does not exist
2023-07-21 22:03:12.758 UTC [1509303] STATEMENT:  CREATE TRANSFORM FOR foo LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:12.759 UTC [1509303] ERROR:  language "foo" does not exist
2023-07-21 22:03:12.759 UTC [1509303] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE foo (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:12.759 UTC [1509303] ERROR:  return data type of FROM SQL function must be internal
2023-07-21 22:03:12.759 UTC [1509303] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_out(hstore), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:12.759 UTC [1509303] ERROR:  first argument of transform function must be type internal
2023-07-21 22:03:12.759 UTC [1509303] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION internal_in(cstring), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:12.760 UTC [1509303] ERROR:  transform for type hstore language "plperl" already exists
2023-07-21 22:03:12.760 UTC [1509303] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:12.766 UTC [1509303] ERROR:  type "foo" does not exist
2023-07-21 22:03:12.766 UTC [1509303] STATEMENT:  DROP TRANSFORM FOR foo LANGUAGE plperl;
2023-07-21 22:03:12.767 UTC [1509303] ERROR:  language "foo" does not exist
2023-07-21 22:03:12.767 UTC [1509303] STATEMENT:  DROP TRANSFORM FOR hstore LANGUAGE foo;
2023-07-21 22:03:12.834 UTC [1509267] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:03:12.869 UTC [1509267] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.010 s, total=0.036 s; sync files=7, longest=0.008 s, average=0.002 s; distance=4474 kB, estimate=4474 kB
2023-07-21 22:03:12.998 UTC [1509330] ERROR:  not a Python mapping
2023-07-21 22:03:12.998 UTC [1509330] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-21 22:03:12.998 UTC [1509330] STATEMENT:  SELECT test1bad();
2023-07-21 22:03:13.011 UTC [1509330] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-21 22:03:13.011 UTC [1509330] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-21 22:03:13.011 UTC [1509330] STATEMENT:  SELECT test2dom('bar');
2023-07-21 22:03:13.039 UTC [1509266] LOG:  received fast shutdown request
2023-07-21 22:03:13.042 UTC [1509266] LOG:  aborting any active transactions
2023-07-21 22:03:13.044 UTC [1509266] LOG:  background worker "logical replication launcher" (PID 1509272) exited with exit code 1
2023-07-21 22:03:13.045 UTC [1509267] LOG:  shutting down
2023-07-21 22:03:13.048 UTC [1509267] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:03:13.123 UTC [1509267] LOG:  checkpoint complete: wrote 907 buffers (5.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.038 s, sync=0.025 s, total=0.079 s; sync files=254, longest=0.004 s, average=0.001 s; distance=4202 kB, estimate=4447 kB
2023-07-21 22:03:13.141 UTC [1509266] LOG:  database system is shut down
2023-07-21 22:03:13.868 UTC [1509361] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:03:13.868 UTC [1509361] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:03:13.874 UTC [1509361] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:03:13.881 UTC [1509364] LOG:  database system was shut down at 2023-07-21 22:03:13 UTC
2023-07-21 22:03:13.886 UTC [1509361] LOG:  database system is ready to accept connections
2023-07-21 22:03:14.103 UTC [1509383] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:03:14.103 UTC [1509383] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:03:14.103 UTC [1509383] STATEMENT:  SELECT test2();
2023-07-21 22:03:14.105 UTC [1509383] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:03:14.105 UTC [1509383] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:03:14.105 UTC [1509383] STATEMENT:  SELECT test2();
2023-07-21 22:03:14.288 UTC [1509395] ERROR:  type "foo" does not exist
2023-07-21 22:03:14.288 UTC [1509395] STATEMENT:  CREATE TRANSFORM FOR foo LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:14.288 UTC [1509395] ERROR:  language "foo" does not exist
2023-07-21 22:03:14.288 UTC [1509395] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE foo (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:14.289 UTC [1509395] ERROR:  return data type of FROM SQL function must be internal
2023-07-21 22:03:14.289 UTC [1509395] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_out(hstore), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:14.289 UTC [1509395] ERROR:  first argument of transform function must be type internal
2023-07-21 22:03:14.289 UTC [1509395] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION internal_in(cstring), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:14.290 UTC [1509395] ERROR:  transform for type hstore language "plperl" already exists
2023-07-21 22:03:14.290 UTC [1509395] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:14.295 UTC [1509395] ERROR:  type "foo" does not exist
2023-07-21 22:03:14.295 UTC [1509395] STATEMENT:  DROP TRANSFORM FOR foo LANGUAGE plperl;
2023-07-21 22:03:14.295 UTC [1509395] ERROR:  language "foo" does not exist
2023-07-21 22:03:14.295 UTC [1509395] STATEMENT:  DROP TRANSFORM FOR hstore LANGUAGE foo;
2023-07-21 22:03:14.328 UTC [1509362] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:03:14.352 UTC [1509362] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.024 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4659 kB, estimate=4659 kB
2023-07-21 22:03:14.537 UTC [1509420] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-21 22:03:14.537 UTC [1509420] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-21 22:03:14.537 UTC [1509420] STATEMENT:  SELECT testComplexNumbers();
2023-07-21 22:03:14.547 UTC [1509361] LOG:  received fast shutdown request
2023-07-21 22:03:14.550 UTC [1509361] LOG:  aborting any active transactions
2023-07-21 22:03:14.550 UTC [1509361] LOG:  background worker "logical replication launcher" (PID 1509367) exited with exit code 1
2023-07-21 22:03:14.550 UTC [1509362] LOG:  shutting down
2023-07-21 22:03:14.553 UTC [1509362] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:03:14.624 UTC [1509362] LOG:  checkpoint complete: wrote 903 buffers (5.5%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.036 s, sync=0.025 s, total=0.074 s; sync files=252, longest=0.009 s, average=0.001 s; distance=4194 kB, estimate=4613 kB
2023-07-21 22:03:14.631 UTC [1509361] LOG:  database system is shut down
2023-07-21 22:03:15.236 UTC [1509451] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:03:15.237 UTC [1509451] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:03:15.242 UTC [1509451] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:03:15.250 UTC [1509454] LOG:  database system was shut down at 2023-07-21 22:03:15 UTC
2023-07-21 22:03:15.255 UTC [1509451] LOG:  database system is ready to accept connections
2023-07-21 22:03:15.463 UTC [1509476] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:03:15.463 UTC [1509476] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:03:15.463 UTC [1509476] STATEMENT:  SELECT test2();
2023-07-21 22:03:15.466 UTC [1509476] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:03:15.466 UTC [1509476] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:03:15.466 UTC [1509476] STATEMENT:  SELECT test2();
2023-07-21 22:03:15.620 UTC [1509488] ERROR:  type "foo" does not exist
2023-07-21 22:03:15.620 UTC [1509488] STATEMENT:  CREATE TRANSFORM FOR foo LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:15.620 UTC [1509488] ERROR:  language "foo" does not exist
2023-07-21 22:03:15.620 UTC [1509488] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE foo (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:15.621 UTC [1509488] ERROR:  return data type of FROM SQL function must be internal
2023-07-21 22:03:15.621 UTC [1509488] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_out(hstore), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:15.622 UTC [1509488] ERROR:  first argument of transform function must be type internal
2023-07-21 22:03:15.622 UTC [1509488] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION internal_in(cstring), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:15.624 UTC [1509488] ERROR:  transform for type hstore language "plperl" already exists
2023-07-21 22:03:15.624 UTC [1509488] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:03:15.629 UTC [1509488] ERROR:  type "foo" does not exist
2023-07-21 22:03:15.629 UTC [1509488] STATEMENT:  DROP TRANSFORM FOR foo LANGUAGE plperl;
2023-07-21 22:03:15.629 UTC [1509488] ERROR:  language "foo" does not exist
2023-07-21 22:03:15.629 UTC [1509488] STATEMENT:  DROP TRANSFORM FOR hstore LANGUAGE foo;
2023-07-21 22:03:15.676 UTC [1509452] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:03:15.707 UTC [1509452] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.011 s, sync=0.008 s, total=0.031 s; sync files=7, longest=0.005 s, average=0.002 s; distance=4962 kB, estimate=4962 kB
2023-07-21 22:03:15.928 UTC [1509516] ERROR:  ltree syntax error at character 1
2023-07-21 22:03:15.928 UTC [1509516] CONTEXT:  while creating return value
	PL/Python function "test2"
2023-07-21 22:03:15.928 UTC [1509516] STATEMENT:  SELECT test2();
2023-07-21 22:03:15.931 UTC [1509451] LOG:  received fast shutdown request
2023-07-21 22:03:15.934 UTC [1509451] LOG:  aborting any active transactions
2023-07-21 22:03:15.935 UTC [1509451] LOG:  background worker "logical replication launcher" (PID 1509457) exited with exit code 1
2023-07-21 22:03:15.935 UTC [1509452] LOG:  shutting down
2023-07-21 22:03:15.938 UTC [1509452] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:03:15.986 UTC [1509452] LOG:  checkpoint complete: wrote 920 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.017 s, sync=0.021 s, total=0.051 s; sync files=252, longest=0.003 s, average=0.001 s; distance=4478 kB, estimate=4913 kB
2023-07-21 22:03:15.993 UTC [1509451] LOG:  database system is shut down
2023-07-21 22:03:16.642 UTC [1509547] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:03:16.642 UTC [1509547] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:03:16.649 UTC [1509547] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:03:16.659 UTC [1509550] LOG:  database system was shut down at 2023-07-21 22:03:16 UTC
2023-07-21 22:03:16.665 UTC [1509547] LOG:  database system is ready to accept connections
2023-07-21 22:03:16.876 UTC [1509572] ERROR:  not a Python mapping
2023-07-21 22:03:16.876 UTC [1509572] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-21 22:03:16.876 UTC [1509572] STATEMENT:  SELECT test1bad();
2023-07-21 22:03:16.884 UTC [1509572] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-21 22:03:16.884 UTC [1509572] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-21 22:03:16.884 UTC [1509572] STATEMENT:  SELECT test2dom('bar');
2023-07-21 22:03:16.934 UTC [1509548] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:03:16.963 UTC [1509548] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.005 s, total=0.029 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4201 kB, estimate=4201 kB
2023-07-21 22:03:48.803 UTC [1509548] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:03:48.901 UTC [1509548] LOG:  checkpoint complete: wrote 703 buffers (4.3%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.018 s, sync=0.036 s, total=0.099 s; sync files=252, longest=0.007 s, average=0.001 s; distance=141042 kB, estimate=141042 kB
2023-07-21 22:04:20.336 UTC [1509548] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:04:20.386 UTC [1509548] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.009 s, sync=0.004 s, total=0.051 s; sync files=4, longest=0.003 s, average=0.001 s; distance=137147 kB, estimate=140652 kB
2023-07-21 22:04:20.454 UTC [1509547] LOG:  received fast shutdown request
2023-07-21 22:04:20.457 UTC [1509547] LOG:  aborting any active transactions
2023-07-21 22:04:20.459 UTC [1509547] LOG:  background worker "logical replication launcher" (PID 1509553) exited with exit code 1
2023-07-21 22:04:20.460 UTC [1509548] LOG:  shutting down
2023-07-21 22:04:20.463 UTC [1509548] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:04:20.482 UTC [1509548] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.023 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126587 kB
2023-07-21 22:04:20.534 UTC [1509547] LOG:  database system is shut down
2023-07-21 22:04:21.138 UTC [1509699] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:04:21.138 UTC [1509699] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:04:21.144 UTC [1509699] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:04:21.155 UTC [1509702] LOG:  database system was shut down at 2023-07-21 22:04:20 UTC
2023-07-21 22:04:21.163 UTC [1509699] LOG:  database system is ready to accept connections
2023-07-21 22:04:21.427 UTC [1509724] ERROR:  not a Python mapping
2023-07-21 22:04:21.427 UTC [1509724] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-21 22:04:21.427 UTC [1509724] STATEMENT:  SELECT test1bad();
2023-07-21 22:04:21.434 UTC [1509724] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-21 22:04:21.434 UTC [1509724] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-21 22:04:21.434 UTC [1509724] STATEMENT:  SELECT test2dom('bar');
2023-07-21 22:04:21.453 UTC [1509700] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:04:21.486 UTC [1509700] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.011 s, sync=0.005 s, total=0.034 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4201 kB, estimate=4201 kB
2023-07-21 22:04:21.614 UTC [1509745] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:04:21.614 UTC [1509745] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:04:21.614 UTC [1509745] STATEMENT:  SELECT test2();
2023-07-21 22:04:21.615 UTC [1509745] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:04:21.615 UTC [1509745] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:04:21.615 UTC [1509745] STATEMENT:  SELECT test2();
2023-07-21 22:04:21.620 UTC [1509745] ERROR:  cannot drop extension hstore because other objects depend on it
2023-07-21 22:04:21.620 UTC [1509745] DETAIL:  extension hstore_plpython3u depends on extension hstore
2023-07-21 22:04:21.620 UTC [1509745] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023-07-21 22:04:21.620 UTC [1509745] STATEMENT:  DROP EXTENSION hstore;
2023-07-21 22:04:21.684 UTC [1509751] ERROR:  cannot drop extension hstore because other objects depend on it
2023-07-21 22:04:21.684 UTC [1509751] DETAIL:  extension hstore_plpython3u depends on extension hstore
2023-07-21 22:04:21.684 UTC [1509751] HINT:  Use DROP ... CASCADE to drop the dependent objects too.
2023-07-21 22:04:21.684 UTC [1509751] STATEMENT:  DROP EXTENSION hstore;
2023-07-21 22:04:21.716 UTC [1509757] ERROR:  type "foo" does not exist
2023-07-21 22:04:21.716 UTC [1509757] STATEMENT:  CREATE TRANSFORM FOR foo LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:04:21.716 UTC [1509757] ERROR:  language "foo" does not exist
2023-07-21 22:04:21.716 UTC [1509757] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE foo (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:04:21.716 UTC [1509757] ERROR:  return data type of FROM SQL function must be internal
2023-07-21 22:04:21.716 UTC [1509757] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_out(hstore), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:04:21.716 UTC [1509757] ERROR:  first argument of transform function must be type internal
2023-07-21 22:04:21.716 UTC [1509757] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION internal_in(cstring), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:04:21.717 UTC [1509757] ERROR:  transform for type hstore language "plperl" already exists
2023-07-21 22:04:21.717 UTC [1509757] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:04:21.722 UTC [1509757] ERROR:  type "foo" does not exist
2023-07-21 22:04:21.722 UTC [1509757] STATEMENT:  DROP TRANSFORM FOR foo LANGUAGE plperl;
2023-07-21 22:04:21.722 UTC [1509757] ERROR:  language "foo" does not exist
2023-07-21 22:04:21.722 UTC [1509757] STATEMENT:  DROP TRANSFORM FOR hstore LANGUAGE foo;
2023-07-21 22:04:21.754 UTC [1509699] LOG:  received fast shutdown request
2023-07-21 22:04:21.757 UTC [1509699] LOG:  aborting any active transactions
2023-07-21 22:04:21.758 UTC [1509699] LOG:  background worker "logical replication launcher" (PID 1509705) exited with exit code 1
2023-07-21 22:04:21.758 UTC [1509700] LOG:  shutting down
2023-07-21 22:04:21.761 UTC [1509700] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:04:21.833 UTC [1509700] LOG:  checkpoint complete: wrote 916 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.043 s, sync=0.019 s, total=0.076 s; sync files=254, longest=0.003 s, average=0.001 s; distance=4475 kB, estimate=4475 kB
2023-07-21 22:04:21.839 UTC [1509699] LOG:  database system is shut down
2023-07-21 22:04:22.447 UTC [1509794] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:04:22.447 UTC [1509794] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:04:22.452 UTC [1509794] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:04:22.459 UTC [1509797] LOG:  database system was shut down at 2023-07-21 22:04:22 UTC
2023-07-21 22:04:22.464 UTC [1509794] LOG:  database system is ready to accept connections
2023-07-21 22:04:22.741 UTC [1509819] ERROR:  not a Python mapping
2023-07-21 22:04:22.741 UTC [1509819] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-21 22:04:22.741 UTC [1509819] STATEMENT:  SELECT test1bad();
2023-07-21 22:04:22.748 UTC [1509819] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-21 22:04:22.748 UTC [1509819] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-21 22:04:22.748 UTC [1509819] STATEMENT:  SELECT test2dom('bar');
2023-07-21 22:04:22.767 UTC [1509795] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:04:22.789 UTC [1509795] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.023 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4201 kB, estimate=4201 kB
2023-07-21 22:04:22.916 UTC [1509840] ERROR:  cannot convert infinity to jsonb
2023-07-21 22:04:22.916 UTC [1509840] CONTEXT:  PL/Perl function "roundtrip"
2023-07-21 22:04:22.916 UTC [1509840] STATEMENT:  SELECT roundtrip('1E+131071');
2023-07-21 22:04:54.705 UTC [1509795] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:04:54.794 UTC [1509795] LOG:  checkpoint complete: wrote 770 buffers (4.7%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.016 s, sync=0.029 s, total=0.090 s; sync files=252, longest=0.004 s, average=0.001 s; distance=140933 kB, estimate=140933 kB
2023-07-21 22:05:26.210 UTC [1509795] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:05:26.270 UTC [1509795] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.009 s, sync=0.008 s, total=0.060 s; sync files=4, longest=0.007 s, average=0.002 s; distance=136582 kB, estimate=140498 kB
2023-07-21 22:05:26.341 UTC [1509794] LOG:  received fast shutdown request
2023-07-21 22:05:26.343 UTC [1509794] LOG:  aborting any active transactions
2023-07-21 22:05:26.344 UTC [1509794] LOG:  background worker "logical replication launcher" (PID 1509800) exited with exit code 1
2023-07-21 22:05:26.344 UTC [1509795] LOG:  shutting down
2023-07-21 22:05:26.347 UTC [1509795] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:05:26.375 UTC [1509795] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.008 s, sync=0.001 s, total=0.031 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126448 kB
2023-07-21 22:05:26.403 UTC [1509794] LOG:  database system is shut down
2023-07-21 22:05:27.041 UTC [1509965] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:05:27.042 UTC [1509965] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:05:27.048 UTC [1509965] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:05:27.057 UTC [1509968] LOG:  database system was shut down at 2023-07-21 22:05:26 UTC
2023-07-21 22:05:27.064 UTC [1509965] LOG:  database system is ready to accept connections
2023-07-21 22:05:27.293 UTC [1509990] ERROR:  cannot convert infinity to jsonb
2023-07-21 22:05:27.293 UTC [1509990] CONTEXT:  PL/Perl function "roundtrip"
2023-07-21 22:05:27.293 UTC [1509990] STATEMENT:  SELECT roundtrip('1E+131071');
2023-07-21 22:05:27.384 UTC [1509966] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:05:27.412 UTC [1509966] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.006 s, total=0.028 s; sync files=7, longest=0.004 s, average=0.001 s; distance=4210 kB, estimate=4210 kB
2023-07-21 22:05:27.612 UTC [1510015] ERROR:  not a Python mapping
2023-07-21 22:05:27.612 UTC [1510015] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-21 22:05:27.612 UTC [1510015] STATEMENT:  SELECT test1bad();
2023-07-21 22:05:27.618 UTC [1510015] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-21 22:05:27.618 UTC [1510015] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-21 22:05:27.618 UTC [1510015] STATEMENT:  SELECT test2dom('bar');
2023-07-21 22:05:59.324 UTC [1509966] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:05:59.428 UTC [1509966] LOG:  checkpoint complete: wrote 764 buffers (4.7%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.040 s, sync=0.024 s, total=0.105 s; sync files=254, longest=0.004 s, average=0.001 s; distance=140872 kB, estimate=140872 kB
2023-07-21 22:06:30.811 UTC [1509966] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:06:30.860 UTC [1509966] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.008 s, sync=0.004 s, total=0.050 s; sync files=4, longest=0.003 s, average=0.001 s; distance=136756 kB, estimate=140460 kB
2023-07-21 22:06:30.899 UTC [1509965] LOG:  received fast shutdown request
2023-07-21 22:06:30.902 UTC [1509965] LOG:  aborting any active transactions
2023-07-21 22:06:30.903 UTC [1509965] LOG:  background worker "logical replication launcher" (PID 1509971) exited with exit code 1
2023-07-21 22:06:30.903 UTC [1509966] LOG:  shutting down
2023-07-21 22:06:30.905 UTC [1509966] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:06:30.921 UTC [1509966] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.019 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126414 kB
2023-07-21 22:06:30.972 UTC [1509965] LOG:  database system is shut down
2023-07-21 22:06:31.609 UTC [1510105] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:06:31.609 UTC [1510105] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:06:31.615 UTC [1510105] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:06:31.625 UTC [1510108] LOG:  database system was shut down at 2023-07-21 22:06:31 UTC
2023-07-21 22:06:31.633 UTC [1510105] LOG:  database system is ready to accept connections
2023-07-21 22:06:31.819 UTC [1510127] ERROR:  cannot convert infinity to jsonb
2023-07-21 22:06:31.819 UTC [1510127] CONTEXT:  PL/Perl function "roundtrip"
2023-07-21 22:06:31.819 UTC [1510127] STATEMENT:  SELECT roundtrip('1E+131071');
2023-07-21 22:06:31.862 UTC [1510106] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:06:31.890 UTC [1510106] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.006 s, total=0.029 s; sync files=7, longest=0.004 s, average=0.001 s; distance=4053 kB, estimate=4053 kB
2023-07-21 22:06:32.014 UTC [1510149] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-21 22:06:32.014 UTC [1510149] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-21 22:06:32.014 UTC [1510149] STATEMENT:  SELECT testComplexNumbers();
2023-07-21 22:07:03.898 UTC [1510106] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:07:04.022 UTC [1510106] LOG:  checkpoint complete: wrote 858 buffers (5.2%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.029 s, sync=0.053 s, total=0.124 s; sync files=252, longest=0.004 s, average=0.001 s; distance=140456 kB, estimate=140456 kB
2023-07-21 22:07:35.425 UTC [1510106] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:07:35.473 UTC [1510106] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.007 s, sync=0.004 s, total=0.049 s; sync files=4, longest=0.003 s, average=0.001 s; distance=136617 kB, estimate=140072 kB
2023-07-21 22:07:35.539 UTC [1510105] LOG:  received fast shutdown request
2023-07-21 22:07:35.542 UTC [1510105] LOG:  aborting any active transactions
2023-07-21 22:07:35.543 UTC [1510105] LOG:  background worker "logical replication launcher" (PID 1510111) exited with exit code 1
2023-07-21 22:07:35.543 UTC [1510106] LOG:  shutting down
2023-07-21 22:07:35.552 UTC [1510106] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:07:35.571 UTC [1510106] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.005 s, sync=0.001 s, total=0.029 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126065 kB
2023-07-21 22:07:35.618 UTC [1510105] LOG:  database system is shut down
2023-07-21 22:07:36.254 UTC [1510249] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:07:36.254 UTC [1510249] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:07:36.260 UTC [1510249] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:07:36.267 UTC [1510252] LOG:  database system was shut down at 2023-07-21 22:07:36 UTC
2023-07-21 22:07:36.272 UTC [1510249] LOG:  database system is ready to accept connections
2023-07-21 22:07:36.504 UTC [1510274] ERROR:  cannot convert infinity to jsonb
2023-07-21 22:07:36.504 UTC [1510274] CONTEXT:  PL/Perl function "roundtrip"
2023-07-21 22:07:36.504 UTC [1510274] STATEMENT:  SELECT roundtrip('1E+131071');
2023-07-21 22:07:36.566 UTC [1510250] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:07:36.595 UTC [1510250] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.010 s, sync=0.006 s, total=0.029 s; sync files=7, longest=0.004 s, average=0.001 s; distance=4358 kB, estimate=4358 kB
2023-07-21 22:07:36.812 UTC [1510299] ERROR:  ltree syntax error at character 1
2023-07-21 22:07:36.812 UTC [1510299] CONTEXT:  while creating return value
	PL/Python function "test2"
2023-07-21 22:07:36.812 UTC [1510299] STATEMENT:  SELECT test2();
2023-07-21 22:08:08.593 UTC [1510250] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:08:08.730 UTC [1510250] LOG:  checkpoint complete: wrote 733 buffers (4.5%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.043 s, sync=0.049 s, total=0.138 s; sync files=252, longest=0.007 s, average=0.001 s; distance=141224 kB, estimate=141224 kB
2023-07-21 22:08:40.103 UTC [1510250] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:08:40.155 UTC [1510250] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.008 s, sync=0.004 s, total=0.053 s; sync files=4, longest=0.003 s, average=0.001 s; distance=137093 kB, estimate=140811 kB
2023-07-21 22:08:40.195 UTC [1510249] LOG:  received fast shutdown request
2023-07-21 22:08:40.198 UTC [1510249] LOG:  aborting any active transactions
2023-07-21 22:08:40.199 UTC [1510249] LOG:  background worker "logical replication launcher" (PID 1510255) exited with exit code 1
2023-07-21 22:08:40.199 UTC [1510250] LOG:  shutting down
2023-07-21 22:08:40.201 UTC [1510250] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:08:40.217 UTC [1510250] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.019 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126730 kB
2023-07-21 22:08:40.237 UTC [1510249] LOG:  database system is shut down
2023-07-21 22:08:40.882 UTC [1510389] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:08:40.882 UTC [1510389] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:08:40.888 UTC [1510389] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:08:40.895 UTC [1510392] LOG:  database system was shut down at 2023-07-21 22:08:40 UTC
2023-07-21 22:08:40.899 UTC [1510389] LOG:  database system is ready to accept connections
2023-07-21 22:08:41.144 UTC [1510411] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-21 22:08:41.144 UTC [1510411] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-21 22:08:41.144 UTC [1510411] STATEMENT:  SELECT testComplexNumbers();
2023-07-21 22:08:41.156 UTC [1510390] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:08:41.180 UTC [1510390] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.025 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4032 kB, estimate=4032 kB
2023-07-21 22:09:13.166 UTC [1510390] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:09:13.292 UTC [1510390] LOG:  checkpoint complete: wrote 415 buffers (2.5%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.014 s, sync=0.028 s, total=0.126 s; sync files=252, longest=0.005 s, average=0.001 s; distance=141095 kB, estimate=141095 kB
2023-07-21 22:09:45.214 UTC [1510390] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:09:45.261 UTC [1510390] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.007 s, sync=0.004 s, total=0.048 s; sync files=4, longest=0.003 s, average=0.001 s; distance=136956 kB, estimate=140681 kB
2023-07-21 22:09:45.322 UTC [1510389] LOG:  received fast shutdown request
2023-07-21 22:09:45.325 UTC [1510389] LOG:  aborting any active transactions
2023-07-21 22:09:45.327 UTC [1510389] LOG:  background worker "logical replication launcher" (PID 1510395) exited with exit code 1
2023-07-21 22:09:45.328 UTC [1510390] LOG:  shutting down
2023-07-21 22:09:45.331 UTC [1510390] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:09:45.353 UTC [1510390] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.025 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126613 kB
2023-07-21 22:09:45.401 UTC [1510389] LOG:  database system is shut down
2023-07-21 22:09:46.019 UTC [1510817] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:09:46.019 UTC [1510817] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:09:46.025 UTC [1510817] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:09:46.031 UTC [1510820] LOG:  database system was shut down at 2023-07-21 22:09:45 UTC
2023-07-21 22:09:46.035 UTC [1510817] LOG:  database system is ready to accept connections
2023-07-21 22:09:46.300 UTC [1510842] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-21 22:09:46.300 UTC [1510842] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-21 22:09:46.300 UTC [1510842] STATEMENT:  SELECT testComplexNumbers();
2023-07-21 22:09:46.312 UTC [1510818] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:09:46.336 UTC [1510818] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.025 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4193 kB, estimate=4193 kB
2023-07-21 22:09:46.433 UTC [1510860] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:09:46.433 UTC [1510860] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:09:46.433 UTC [1510860] STATEMENT:  SELECT test2();
2023-07-21 22:09:46.435 UTC [1510860] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:09:46.435 UTC [1510860] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:09:46.435 UTC [1510860] STATEMENT:  SELECT test2();
2023-07-21 22:09:46.555 UTC [1510872] ERROR:  type "foo" does not exist
2023-07-21 22:09:46.555 UTC [1510872] STATEMENT:  CREATE TRANSFORM FOR foo LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:09:46.555 UTC [1510872] ERROR:  language "foo" does not exist
2023-07-21 22:09:46.555 UTC [1510872] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE foo (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:09:46.555 UTC [1510872] ERROR:  return data type of FROM SQL function must be internal
2023-07-21 22:09:46.555 UTC [1510872] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_out(hstore), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:09:46.556 UTC [1510872] ERROR:  first argument of transform function must be type internal
2023-07-21 22:09:46.556 UTC [1510872] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION internal_in(cstring), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:09:46.557 UTC [1510872] ERROR:  transform for type hstore language "plperl" already exists
2023-07-21 22:09:46.557 UTC [1510872] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:09:46.561 UTC [1510872] ERROR:  type "foo" does not exist
2023-07-21 22:09:46.561 UTC [1510872] STATEMENT:  DROP TRANSFORM FOR foo LANGUAGE plperl;
2023-07-21 22:09:46.561 UTC [1510872] ERROR:  language "foo" does not exist
2023-07-21 22:09:46.561 UTC [1510872] STATEMENT:  DROP TRANSFORM FOR hstore LANGUAGE foo;
2023-07-21 22:09:46.579 UTC [1510817] LOG:  received fast shutdown request
2023-07-21 22:09:46.582 UTC [1510817] LOG:  aborting any active transactions
2023-07-21 22:09:46.582 UTC [1510817] LOG:  background worker "logical replication launcher" (PID 1510823) exited with exit code 1
2023-07-21 22:09:46.582 UTC [1510818] LOG:  shutting down
2023-07-21 22:09:46.585 UTC [1510818] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:09:46.629 UTC [1510818] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.013 s, sync=0.022 s, total=0.047 s; sync files=254, longest=0.006 s, average=0.001 s; distance=4660 kB, estimate=4660 kB
2023-07-21 22:09:46.634 UTC [1510817] LOG:  database system is shut down
2023-07-21 22:09:47.298 UTC [1510907] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:09:47.299 UTC [1510907] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:09:47.304 UTC [1510907] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:09:47.312 UTC [1510910] LOG:  database system was shut down at 2023-07-21 22:09:47 UTC
2023-07-21 22:09:47.317 UTC [1510907] LOG:  database system is ready to accept connections
2023-07-21 22:09:47.496 UTC [1510929] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-21 22:09:47.496 UTC [1510929] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-21 22:09:47.496 UTC [1510929] STATEMENT:  SELECT testComplexNumbers();
2023-07-21 22:09:47.508 UTC [1510908] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:09:47.532 UTC [1510908] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.024 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4032 kB, estimate=4032 kB
2023-07-21 22:09:47.638 UTC [1510947] ERROR:  cannot convert infinity to jsonb
2023-07-21 22:09:47.638 UTC [1510947] CONTEXT:  PL/Perl function "roundtrip"
2023-07-21 22:09:47.638 UTC [1510947] STATEMENT:  SELECT roundtrip('1E+131071');
2023-07-21 22:10:19.508 UTC [1510908] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:10:19.588 UTC [1510908] LOG:  checkpoint complete: wrote 901 buffers (5.5%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.019 s, sync=0.022 s, total=0.080 s; sync files=252, longest=0.006 s, average=0.001 s; distance=140340 kB, estimate=140340 kB
2023-07-21 22:10:51.022 UTC [1510908] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:10:51.071 UTC [1510908] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.009 s, sync=0.004 s, total=0.050 s; sync files=4, longest=0.003 s, average=0.001 s; distance=136722 kB, estimate=139978 kB
2023-07-21 22:10:51.128 UTC [1510907] LOG:  received fast shutdown request
2023-07-21 22:10:51.131 UTC [1510907] LOG:  aborting any active transactions
2023-07-21 22:10:51.132 UTC [1510907] LOG:  background worker "logical replication launcher" (PID 1510913) exited with exit code 1
2023-07-21 22:10:51.132 UTC [1510908] LOG:  shutting down
2023-07-21 22:10:51.134 UTC [1510908] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:10:51.155 UTC [1510908] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.004 s, sync=0.001 s, total=0.023 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=125981 kB
2023-07-21 22:10:51.181 UTC [1510907] LOG:  database system is shut down
2023-07-21 22:10:51.831 UTC [1511041] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:10:51.831 UTC [1511041] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:10:51.836 UTC [1511041] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:10:51.843 UTC [1511044] LOG:  database system was shut down at 2023-07-21 22:10:51 UTC
2023-07-21 22:10:51.847 UTC [1511041] LOG:  database system is ready to accept connections
2023-07-21 22:10:52.082 UTC [1511066] ERROR:  ltree syntax error at character 1
2023-07-21 22:10:52.082 UTC [1511066] CONTEXT:  while creating return value
	PL/Python function "test2"
2023-07-21 22:10:52.082 UTC [1511066] STATEMENT:  SELECT test2();
2023-07-21 22:10:52.090 UTC [1511042] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:10:52.113 UTC [1511042] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.005 s, total=0.024 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4324 kB, estimate=4324 kB
2023-07-21 22:11:24.086 UTC [1511042] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:11:24.189 UTC [1511042] LOG:  checkpoint complete: wrote 696 buffers (4.2%); 0 WAL file(s) added, 0 removed, 9 recycled; write=0.034 s, sync=0.030 s, total=0.104 s; sync files=252, longest=0.006 s, average=0.001 s; distance=141337 kB, estimate=141337 kB
2023-07-21 22:11:55.606 UTC [1511042] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:11:55.659 UTC [1511042] LOG:  checkpoint complete: wrote 11 buffers (0.1%); 0 WAL file(s) added, 0 removed, 8 recycled; write=0.012 s, sync=0.004 s, total=0.054 s; sync files=4, longest=0.003 s, average=0.001 s; distance=137030 kB, estimate=140906 kB
2023-07-21 22:11:55.721 UTC [1511041] LOG:  received fast shutdown request
2023-07-21 22:11:55.724 UTC [1511041] LOG:  aborting any active transactions
2023-07-21 22:11:55.725 UTC [1511041] LOG:  background worker "logical replication launcher" (PID 1511047) exited with exit code 1
2023-07-21 22:11:55.725 UTC [1511042] LOG:  shutting down
2023-07-21 22:11:55.728 UTC [1511042] LOG:  checkpoint starting: shutdown immediate
2023-07-21 22:11:55.743 UTC [1511042] LOG:  checkpoint complete: wrote 1 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.003 s, sync=0.001 s, total=0.018 s; sync files=1, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=126816 kB
2023-07-21 22:11:55.769 UTC [1511041] LOG:  database system is shut down
2023-07-21 22:11:56.454 UTC [1511214] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-21 22:11:56.454 UTC [1511214] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-21 22:11:56.460 UTC [1511214] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-21 22:11:56.466 UTC [1511217] LOG:  database system was shut down at 2023-07-21 22:11:56 UTC
2023-07-21 22:11:56.471 UTC [1511214] LOG:  database system is ready to accept connections
2023-07-21 22:11:56.658 UTC [1511242] ERROR:  ltree syntax error at character 1
2023-07-21 22:11:56.658 UTC [1511242] CONTEXT:  while creating return value
	PL/Python function "test2"
2023-07-21 22:11:56.658 UTC [1511242] STATEMENT:  SELECT test2();
2023-07-21 22:11:56.666 UTC [1511215] LOG:  checkpoint starting: immediate force wait
2023-07-21 22:11:56.692 UTC [1511215] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.005 s, total=0.027 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4477 kB, estimate=4477 kB
2023-07-21 22:11:56.830 UTC [1511263] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:11:56.830 UTC [1511263] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:11:56.830 UTC [1511263] STATEMENT:  SELECT test2();
2023-07-21 22:11:56.831 UTC [1511263] ERROR:  cannot transform non-hash Perl value to hstore
2023-07-21 22:11:56.831 UTC [1511263] CONTEXT:  PL/Perl function "test2"
2023-07-21 22:11:56.831 UTC [1511263] STATEMENT:  SELECT test2();
2023-07-21 22:11:56.926 UTC [1511275] ERROR:  type "foo" does not exist
2023-07-21 22:11:56.926 UTC [1511275] STATEMENT:  CREATE TRANSFORM FOR foo LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:11:56.926 UTC [1511275] ERROR:  language "foo" does not exist
2023-07-21 22:11:56.926 UTC [1511275] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE foo (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:11:56.927 UTC [1511275] ERROR:  return data type of FROM SQL function must be internal
2023-07-21 22:11:56.927 UTC [1511275] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_out(hstore), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:11:56.927 UTC [1511275] ERROR:  first argument of transform function must be type internal
2023-07-21 22:11:56.927 UTC [1511275] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION internal_in(cstring), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:11:56.928 UTC [1511275] ERROR:  transform for type hstore language "plperl" already exists
2023-07-21 22:11:56.928 UTC [1511275] STATEMENT:  CREATE TRANSFORM FOR hstore LANGUAGE plperl (FROM SQL WITH FUNCTION hstore_to_plperl(internal), TO SQL WITH FUNCTION plperl_to_hstore(internal));
2023-07-21 22:11:56.931 UTC [1511275] ERROR:  type "foo" does not exist
2023-07-21 22:11:56.931 UTC [1511275] STATEMENT:  DROP TRANSFORM FOR foo LANGUAGE plperl;
2023-07-21 22:11:56.932 UTC [1511275] ERROR:  language "foo" does not exist
2023-07-21 22:11:56.932 UTC [1511275] STATEMENT:  DROP TRANSFORM FOR hstore LANGUAGE foo;
