2023-07-26 23:36:34.887 UTC [2192169] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-26 23:36:34.887 UTC [2192169] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-26 23:36:34.893 UTC [2192169] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-26 23:36:34.902 UTC [2192172] LOG:  database system was shut down at 2023-07-26 23:36:34 UTC
2023-07-26 23:36:34.908 UTC [2192169] LOG:  database system is ready to accept connections
2023-07-26 23:36:35.102 UTC [2192188] ERROR:  not a Python mapping
2023-07-26 23:36:35.102 UTC [2192188] CONTEXT:  while creating return value
	PL/Python function "test1bad"
2023-07-26 23:36:35.102 UTC [2192188] STATEMENT:  SELECT test1bad();
2023-07-26 23:36:35.110 UTC [2192188] ERROR:  value for domain hstore_foo violates check constraint "hstore_foo_check"
2023-07-26 23:36:35.110 UTC [2192188] CONTEXT:  while creating return value
	PL/Python function "test2dom"
2023-07-26 23:36:35.110 UTC [2192188] STATEMENT:  SELECT test2dom('bar');
2023-07-26 23:36:35.158 UTC [2192170] LOG:  checkpoint starting: immediate force wait
2023-07-26 23:36:35.187 UTC [2192170] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.009 s, sync=0.005 s, total=0.029 s; sync files=7, longest=0.003 s, average=0.001 s; distance=4193 kB, estimate=4193 kB
2023-07-26 23:36:35.268 UTC [2192204] ERROR:  required extension "hstore" is not installed
2023-07-26 23:36:35.268 UTC [2192204] HINT:  Use CREATE EXTENSION ... CASCADE to install required extensions too.
2023-07-26 23:36:35.268 UTC [2192204] STATEMENT:  CREATE EXTENSION IF NOT EXISTS "hstore_plpython3u"
