2023-07-26 10:13:53.275 UTC [2066627] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-26 10:13:53.275 UTC [2066627] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-26 10:13:53.291 UTC [2066627] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-26 10:13:53.306 UTC [2066630] LOG:  database system was shut down at 2023-07-26 10:13:52 UTC
2023-07-26 10:13:53.315 UTC [2066627] LOG:  database system is ready to accept connections
2023-07-26 10:13:53.822 UTC [2066648] WARNING:  hypopg: SQL order #1 is not a CREATE INDEX statement
2023-07-26 10:13:53.822 UTC [2066648] WARNING:  hypopg: SQL order #3 is not a CREATE INDEX statement
2023-07-26 10:13:53.825 UTC [2066648] ERROR:  value 1 out of bounds for option "fillfactor"
2023-07-26 10:13:53.825 UTC [2066648] DETAIL:  Valid values are between "10" and "100".
2023-07-26 10:13:53.825 UTC [2066648] STATEMENT:  SELECT COUNT(*) AS NB
	FROM public.hypopg_create_index('CREATE INDEX ON hypo(id) WITH (fillfactor = 1)');
2023-07-26 10:13:53.825 UTC [2066648] ERROR:  oid 1 is not a hypothetical index
2023-07-26 10:13:53.825 UTC [2066648] STATEMENT:  SELECT hypopg_relation_size(1);
2023-07-26 10:13:54.884 UTC [2066628] LOG:  checkpoint starting: immediate force wait
2023-07-26 10:13:55.136 UTC [2066628] LOG:  checkpoint complete: wrote 3299 buffers (20.1%); 0 WAL file(s) added, 0 removed, 2 recycled; write=0.084 s, sync=0.119 s, total=0.252 s; sync files=750, longest=0.040 s, average=0.001 s; distance=29725 kB, estimate=29725 kB
2023-07-26 10:13:55.163 UTC [2066628] LOG:  checkpoint starting: immediate force wait
2023-07-26 10:13:55.217 UTC [2066628] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.011 s, total=0.055 s; sync files=2, longest=0.008 s, average=0.006 s; distance=1 kB, estimate=26752 kB
2023-07-26 10:13:55.354 UTC [2066708] ERROR:  current user cannot be dropped
2023-07-26 10:13:55.354 UTC [2066708] STATEMENT:  DROP USER su;
2023-07-26 10:13:55.821 UTC [2066628] LOG:  checkpoint starting: immediate force wait
2023-07-26 10:13:55.935 UTC [2066628] LOG:  checkpoint complete: wrote 1016 buffers (6.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.049 s, sync=0.031 s, total=0.114 s; sync files=297, longest=0.010 s, average=0.001 s; distance=8804 kB, estimate=24957 kB
2023-07-26 10:13:55.985 UTC [2066628] LOG:  checkpoint starting: immediate force wait
2023-07-26 10:13:56.041 UTC [2066628] LOG:  checkpoint complete: wrote 10 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.011 s, total=0.057 s; sync files=7, longest=0.008 s, average=0.002 s; distance=45 kB, estimate=22466 kB
2023-07-26 10:13:56.160 UTC [2066736] ERROR:  duplicate key value violates unique constraint "company_pkey"
2023-07-26 10:13:56.160 UTC [2066736] DETAIL:  Key (id)=(1) already exists.
2023-07-26 10:13:56.160 UTC [2066736] STATEMENT:  INSERT  INTO Company(ID, Name) VALUES (1, 'Percona');
2023-07-26 10:13:56.412 UTC [2066756] ERROR:  division by zero
2023-07-26 10:13:56.412 UTC [2066756] STATEMENT:  SELECT 1/0;
2023-07-26 10:13:56.413 UTC [2066756] ERROR:  relation "unknown" does not exist at character 15
2023-07-26 10:13:56.413 UTC [2066756] STATEMENT:  SELECT * FROM unknown;
2023-07-26 10:13:56.413 UTC [2066756] ERROR:  syntax error at or near "ELECET" at character 1
2023-07-26 10:13:56.413 UTC [2066756] STATEMENT:  ELECET * FROM unknown;
2023-07-26 10:13:56.414 UTC [2066756] WARNING:  warning message
2023-07-26 10:13:56.414 UTC [2066756] CONTEXT:  PL/pgSQL function inline_code_block line 3 at RAISE
2023-07-26 10:13:56.566 UTC [2066770] ERROR:  role "su" already exists
2023-07-26 10:13:56.566 UTC [2066770] STATEMENT:  CREATE USER su WITH SUPERUSER;
2023-07-26 10:13:56.596 UTC [2066770] ERROR:  permission denied for function pg_stat_monitor_reset
2023-07-26 10:13:56.596 UTC [2066770] STATEMENT:  SELECT pg_stat_monitor_reset();
