2023-07-27 01:58:52.362 UTC [2213491] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
2023-07-27 01:58:52.362 UTC [2213491] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-07-27 01:58:52.377 UTC [2213491] LOG:  listening on Unix socket "/tmp/.s.PGSQL.5432"
2023-07-27 01:58:52.393 UTC [2213494] LOG:  database system was shut down at 2023-07-27 01:58:51 UTC
2023-07-27 01:58:52.401 UTC [2213491] LOG:  database system is ready to accept connections
2023-07-27 01:58:52.679 UTC [2213510] ERROR:  could not convert value "(1+2j)" to jsonb
2023-07-27 01:58:52.679 UTC [2213510] CONTEXT:  while creating return value
	PL/Python function "testcomplexnumbers"
2023-07-27 01:58:52.679 UTC [2213510] STATEMENT:  SELECT testComplexNumbers();
2023-07-27 01:58:52.703 UTC [2213492] LOG:  checkpoint starting: immediate force wait
2023-07-27 01:58:52.774 UTC [2213492] LOG:  checkpoint complete: wrote 9 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.022 s, sync=0.014 s, total=0.072 s; sync files=7, longest=0.008 s, average=0.002 s; distance=4091 kB, estimate=4091 kB
2023-07-27 01:58:53.362 UTC [2213492] LOG:  checkpoint starting: immediate force wait
2023-07-27 01:58:53.536 UTC [2213492] LOG:  checkpoint complete: wrote 1795 buffers (11.0%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.064 s, sync=0.068 s, total=0.174 s; sync files=497, longest=0.021 s, average=0.001 s; distance=12320 kB, estimate=12320 kB
2023-07-27 01:58:53.561 UTC [2213492] LOG:  checkpoint starting: immediate force wait
2023-07-27 01:58:53.619 UTC [2213492] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.011 s, total=0.058 s; sync files=2, longest=0.008 s, average=0.006 s; distance=1 kB, estimate=11088 kB
2023-07-27 01:58:53.736 UTC [2213553] ERROR:  current user cannot be dropped
2023-07-27 01:58:53.736 UTC [2213553] STATEMENT:  DROP USER su;
2023-07-27 01:58:54.272 UTC [2213492] LOG:  checkpoint starting: immediate force wait
2023-07-27 01:58:54.383 UTC [2213492] LOG:  checkpoint complete: wrote 1015 buffers (6.2%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.049 s, sync=0.031 s, total=0.112 s; sync files=297, longest=0.009 s, average=0.001 s; distance=8786 kB, estimate=10858 kB
2023-07-27 01:58:54.425 UTC [2213492] LOG:  checkpoint starting: immediate force wait
2023-07-27 01:58:54.481 UTC [2213492] LOG:  checkpoint complete: wrote 8 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.012 s, sync=0.011 s, total=0.057 s; sync files=7, longest=0.008 s, average=0.002 s; distance=34 kB, estimate=9776 kB
2023-07-27 01:58:54.575 UTC [2213581] ERROR:  duplicate key value violates unique constraint "company_pkey"
2023-07-27 01:58:54.575 UTC [2213581] DETAIL:  Key (id)=(1) already exists.
2023-07-27 01:58:54.575 UTC [2213581] STATEMENT:  INSERT  INTO Company(ID, Name) VALUES (1, 'Percona');
2023-07-27 01:58:54.787 UTC [2213601] ERROR:  division by zero
2023-07-27 01:58:54.787 UTC [2213601] STATEMENT:  SELECT 1/0;
2023-07-27 01:58:54.787 UTC [2213601] ERROR:  relation "unknown" does not exist at character 15
2023-07-27 01:58:54.787 UTC [2213601] STATEMENT:  SELECT * FROM unknown;
2023-07-27 01:58:54.787 UTC [2213601] ERROR:  syntax error at or near "ELECET" at character 1
2023-07-27 01:58:54.787 UTC [2213601] STATEMENT:  ELECET * FROM unknown;
2023-07-27 01:58:54.788 UTC [2213601] WARNING:  warning message
2023-07-27 01:58:54.788 UTC [2213601] CONTEXT:  PL/pgSQL function inline_code_block line 3 at RAISE
2023-07-27 01:58:54.910 UTC [2213615] ERROR:  role "su" already exists
2023-07-27 01:58:54.910 UTC [2213615] STATEMENT:  CREATE USER su WITH SUPERUSER;
2023-07-27 01:58:54.938 UTC [2213615] ERROR:  permission denied for function pg_stat_monitor_reset
2023-07-27 01:58:54.938 UTC [2213615] STATEMENT:  SELECT pg_stat_monitor_reset();
